name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: RepositoriesForPoc/Resuable-Workflow-Called/.github/workflows/reusable-workflow.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "demo"
